version: "3.1"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: magma
      POSTGRES_PASSWORD: magma
      POSTGRES_DB: plankton
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend
#
#  api:
#    build:
#      context: .
#      dockerfile: ./docker/api/Dockerfile
#    container_name: api
#    ports:
#      - "8080:8080"
#    volumes:
#      - /Users/Ruffles/Projects/plankton/plankton/backend/src/main/resources/static/img:/app/backend/src/main/resources/static/img
#    depends_on:
#      - postgres
#    networks:
#      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
